import base64
import os

png_base64 = b"iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABH0lEQVR42u3cwW0CQRADUJs0QiWkEDph/9VRyWkETvCTZ0ey4/E8z/O8v02/3++3x+Px72/d3u/3t+12+3r+7XYbbwHwE4AAAgAAAAkAAAJAAACQAACQAAAggAAAIAAAJAAACAAAAEgAABAAAAAQAAAkAAAIAAAJAAASAAAEAAAIAAAJAAACAAAkAAAIAMArANfr9XY8Hj/P//1+j/N4C4AXAEC8AAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAHr2B1+y/y5p/gN1AAAAAElFTkSuQmCC"

with open("d:/sery17-main/sery17-main/frontend/public/favicon.ico", "wb") as f:
    f.write(base64.b64decode(png_base64))
with open("d:/sery17-main/sery17-main/frontend/public/favicon.png", "wb") as f:
    f.write(base64.b64decode(png_base64))
print("Created favicon.ico and favicon.png")
